ChannelSelection Subservice
openatv/enigma2 pull request #3266
Opened 2024-03-06 21:27 UTC by jbleyel

[ChannelSelection]
- create, fill and refill a virtual (groupedservices.virtualsubservices.tv) bouquet
- if subservices available, they can be entered via
  - "Reception Lists"
  - ChannelContextMenu new item added
  - Hotkey

[InfoBarGenerics]
- add method for ButtonSetup

[ButtonSetup]
- append "Show subservices"

[EpgSelection]
- provide a subservicelist for all EPG's

2024-04-04 07:03 UTC, IanSav commented
This code causes a boot loop.  This code can not be merged.

2024-04-04 07:07 UTC, IanSav requested changes
This code can't be merged as it creates a boot loop.  The boot loop makes it impossible to test the code.

I will look at the code and try to create a working version.

2024-04-04 07:07 UTC, IanSav commented on lib/python/Screens/EpgSelection.py
> +from Screens.InfoBar import InfoBar
This import causes a boot loop. This code can not be merged.

2024-04-04 18:00 UTC, GhostofGeeeee commented
Looks feasible, but it's not my branch...

2024-04-04 18:55 UTC, jbleyel commented
> Looks feasible, but it's not my branch...

It's your commit :

https://github.com/GhostofGeeeee/enigma2/commit/3a86d5c6cdb22974908b3ae468658c8815556b76#diff-70806cbca1d82e0e3d304147ae4ecb5ea53bfc085062721bf79ee5c954ddf532

;-)

2024-04-06 08:11 UTC, GhostofGeeeee commented
This is not my PR.

2024-04-06 08:22 UTC, jbleyel commented
> This is not my PR.

Yes it is.

https://github.com/openatv/enigma2/pull/3265

2024-04-07 08:52 UTC, GhostofGeeeee commented
And how to fix a commit or a closed PR?

2024-04-07 08:57 UTC, jbleyel commented
We are currently working on this task.

2024-04-18 15:43 UTC, merged